# Index constants for accessing data in the Data Handler

class CDH_IDX:
    TIME = 0
    SC_STATE = 1
    SD_USAGE = 2
    CURRENT_RAM_USAGE = 3
    REBOOT_COUNT = 4
    WATCHDOG_TIMER = 5
    HAL_BITFLAGS = 6
    DETUMBLING_ERROR_FLAG = 7


class EPS_IDX:
    TIME_EPS = 0
    EPS_POWER_FLAG = 1
    MAINBOARD_TEMPERATURE = 2
    MAINBOARD_VOLTAGE = 3
    MAINBOARD_CURRENT = 4
    BATTERY_PACK_TEMPERATURE = 5
    BATTERY_PACK_REPORTED_SOC = 6
    BATTERY_PACK_REPORTED_CAPACITY = 7
    BATTERY_PACK_CURRENT = 8
    BATTERY_PACK_VOLTAGE = 9
    BATTERY_PACK_MIDPOINT_VOLTAGE = 10
    BATTERY_PACK_TTE = 11
    BATTERY_PACK_TTF = 12
    XP_COIL_VOLTAGE = 13
    XP_COIL_CURRENT = 14
    XM_COIL_VOLTAGE = 15
    XM_COIL_CURRENT = 16
    YP_COIL_VOLTAGE = 17
    YP_COIL_CURRENT = 18
    YM_COIL_VOLTAGE = 19
    YM_COIL_CURRENT = 20
    ZP_COIL_VOLTAGE = 21
    ZP_COIL_CURRENT = 22
    ZM_COIL_VOLTAGE = 23
    ZM_COIL_CURRENT = 24
    JETSON_INPUT_VOLTAGE = 25
    JETSON_INPUT_CURRENT = 26
    RF_LDO_OUTPUT_VOLTAGE = 27
    RF_LDO_OUTPUT_CURRENT = 28
    GPS_VOLTAGE = 29
    GPS_CURRENT = 30
    XP_SOLAR_CHARGE_VOLTAGE = 31
    XP_SOLAR_CHARGE_CURRENT = 32
    XM_SOLAR_CHARGE_VOLTAGE = 33
    XM_SOLAR_CHARGE_CURRENT = 34
    YP_SOLAR_CHARGE_VOLTAGE = 35
    YP_SOLAR_CHARGE_CURRENT = 36
    YM_SOLAR_CHARGE_VOLTAGE = 37
    YM_SOLAR_CHARGE_CURRENT = 38
    ZP_SOLAR_CHARGE_VOLTAGE = 39
    ZP_SOLAR_CHARGE_CURRENT = 40
    ZM_SOLAR_CHARGE_VOLTAGE = 41
    ZM_SOLAR_CHARGE_CURRENT = 42


class EPS_WARNING_IDX:
    TIME_EPS_WARNING = 0
    MAINBOARD_POWER_ALERT = 1
    RADIO_POWER_ALERT = 2
    JETSON_POWER_ALERT = 3
    XP_COIL_POWER_ALERT = 4
    XM_COIL_POWER_ALERT = 5
    YP_COIL_POWER_ALERT = 6
    YM_COIL_POWER_ALERT = 7
    ZP_COIL_POWER_ALERT = 8
    ZM_COIL_POWER_ALERT = 9


class ADCS_IDX:
    TIME_ADCS = 0
    MODE = 1
    GYRO_X = 2
    GYRO_Y = 3
    GYRO_Z = 4
    MAG_X = 5
    MAG_Y = 6
    MAG_Z = 7
    SUN_STATUS = 8
    SUN_VEC_X = 9
    SUN_VEC_Y = 10
    SUN_VEC_Z = 11
    LIGHT_SENSOR_XP = 12
    LIGHT_SENSOR_XM = 13
    LIGHT_SENSOR_YP = 14
    LIGHT_SENSOR_YM = 15
    LIGHT_SENSOR_ZP1 = 16
    LIGHT_SENSOR_ZP2 = 17
    LIGHT_SENSOR_ZP3 = 18
    LIGHT_SENSOR_ZP4 = 19
    LIGHT_SENSOR_ZM = 20
    XP_COIL_STATUS = 21
    XM_COIL_STATUS = 22
    YP_COIL_STATUS = 23
    YM_COIL_STATUS = 24
    ZP_COIL_STATUS = 25
    ZM_COIL_STATUS = 26
    ATTITUDE_QW = 27
    ATTITUDE_QX = 28
    ATTITUDE_QY = 29
    ATTITUDE_QZ = 30


class IMU_IDX:
    TIME_IMU = 0
    ACCEL_X = 1
    ACCEL_Y = 2
    ACCEL_Z = 3
    MAGNETOMETER_X = 4
    MAGNETOMETER_Y = 5
    MAGNETOMETER_Z = 6
    GYROSCOPE_X = 7
    GYROSCOPE_Y = 8
    GYROSCOPE_Z = 9


class GPS_IDX:
    TIME_GPS = 0
    GPS_MESSAGE_ID = 1
    GPS_FIX_MODE = 2
    GPS_NUMBER_OF_SV = 3
    GPS_GNSS_WEEK = 4
    GPS_GNSS_TOW = 5
    GPS_LATITUDE = 6
    GPS_LONGITUDE = 7
    GPS_ELLIPSOID_ALT = 8
    GPS_MEAN_SEA_LVL_ALT = 9
    GPS_GDOP = 10
    GPS_PDOP = 11
    GPS_HDOP = 12
    GPS_VDOP = 13
    GPS_TDOP = 14
    GPS_ECEF_X = 15
    GPS_ECEF_Y = 16
    GPS_ECEF_Z = 17
    GPS_ECEF_VX = 18
    GPS_ECEF_VY = 19
    GPS_ECEF_VZ = 20


class PAYLOAD_IDX:
    pass


class STORAGE_IDX:
    NUM_FILES = 0
    DIR_SIZE = 1


"""
Helper function to get the number of attributes in a class
This result should be static
"""


def class_length(cls):
    return len([attr for attr in dir(cls) if not callable(getattr(cls, attr)) and not attr.startswith("__")])
